# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/3rok/5semestr/io.nosync/scrabble/Scrabble_with_GUI/Scrabble_with_GUI/templates/replay_manager_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_replay_manager_window(object):
    def setupUi(self, replay_manager_window):
        replay_manager_window.setObjectName("replay_manager_window")
        replay_manager_window.resize(330, 280)
        self.centralwidget = QtWidgets.QWidget(replay_manager_window)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(10, 10, 311, 261))
        self.menu_frame.setStyleSheet("QFrame {\n"
"    border-radius: 7px;\n"
"    color: rgb(62, 231, 41);\n"
"    background-color: rgb(40, 109, 50);\n"
"}\n"
"")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.name_label = QtWidgets.QLabel(self.menu_frame)
        self.name_label.setGeometry(QtCore.QRect(-40, 20, 361, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.exit_button = QtWidgets.QPushButton(self.menu_frame)
        self.exit_button.setGeometry(QtCore.QRect(290, 7, 14, 14))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setCheckable(False)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.game_id_label = QtWidgets.QLabel(self.menu_frame)
        self.game_id_label.setGeometry(QtCore.QRect(50, 90, 58, 31))
        self.game_id_label.setObjectName("game_id_label")
        self.current_player_label = QtWidgets.QLabel(self.menu_frame)
        self.current_player_label.setGeometry(QtCore.QRect(120, 130, 181, 31))
        self.current_player_label.setStyleSheet("QLabel{\n"
"    color: beige;\n"
"}")
        self.current_player_label.setObjectName("current_player_label")
        self.player_icon_label = QtWidgets.QLabel(self.menu_frame)
        self.player_icon_label.setGeometry(QtCore.QRect(60, 120, 40, 40))
        self.player_icon_label.setText("")
        self.player_icon_label.setObjectName("player_icon_label")
        self.label = QtWidgets.QLabel(self.menu_frame)
        self.label.setGeometry(QtCore.QRect(30, 180, 111, 31))
        self.label.setObjectName("label")
        self.next_player_label = QtWidgets.QLabel(self.menu_frame)
        self.next_player_label.setGeometry(QtCore.QRect(150, 180, 161, 31))
        self.next_player_label.setStyleSheet("QLabel{\n"
"    color: beige;\n"
"}")
        self.next_player_label.setObjectName("next_player_label")
        self.prev_move_button = QtWidgets.QPushButton(self.menu_frame)
        self.prev_move_button.setGeometry(QtCore.QRect(70, 220, 71, 32))
        self.prev_move_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"}")
        self.prev_move_button.setText("")
        self.prev_move_button.setObjectName("prev_move_button")
        self.next_move_button = QtWidgets.QPushButton(self.menu_frame)
        self.next_move_button.setGeometry(QtCore.QRect(170, 220, 61, 32))
        self.next_move_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"}")
        self.next_move_button.setText("")
        self.next_move_button.setObjectName("next_move_button")
        self.status_label = QtWidgets.QLabel(self.menu_frame)
        self.status_label.setGeometry(QtCore.QRect(130, 95, 161, 21))
        self.status_label.setObjectName("status_label")
        replay_manager_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(replay_manager_window)
        QtCore.QMetaObject.connectSlotsByName(replay_manager_window)

    def retranslateUi(self, replay_manager_window):
        _translate = QtCore.QCoreApplication.translate
        replay_manager_window.setWindowTitle(_translate("replay_manager_window", "MainWindow"))
        self.name_label.setText(_translate("replay_manager_window", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble</span></p><p><br/></p></body></html>"))
        self.game_id_label.setText(_translate("replay_manager_window", "TextLabel"))
        self.current_player_label.setText(_translate("replay_manager_window", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; font-style:italic;\">current player</span></p><p><br/></p></body></html>"))
        self.label.setText(_translate("replay_manager_window", "next player: "))
        self.next_player_label.setText(_translate("replay_manager_window", "new word pholder"))
        self.status_label.setText(_translate("replay_manager_window", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    replay_manager_window = QtWidgets.QMainWindow()
    ui = Ui_replay_manager_window()
    ui.setupUi(replay_manager_window)
    replay_manager_window.show()
    sys.exit(app.exec())
