# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/3rok/5semestr/io.nosync/scrabble/Scrabble_with_GUI/Scrabble_with_GUI/templates/replay_select_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_replay_select_window(object):
    def setupUi(self, replay_select_window):
        replay_select_window.setObjectName("replay_select_window")
        replay_select_window.resize(600, 650)
        self.centralwidget = QtWidgets.QWidget(replay_select_window)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(140, 60, 391, 501))
        self.menu_frame.setStyleSheet("QFrame {\n"
"    border-radius: 7px;\n"
"    color: rgb(62, 231, 41);\n"
"    background-color: rgb(40, 109, 50);\n"
"}\n"
"")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.name_label = QtWidgets.QLabel(self.menu_frame)
        self.name_label.setGeometry(QtCore.QRect(-40, 10, 361, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.exit_button = QtWidgets.QPushButton(self.menu_frame)
        self.exit_button.setGeometry(QtCore.QRect(370, 10, 14, 14))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setCheckable(False)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.game_mode_frame = QtWidgets.QFrame(self.menu_frame)
        self.game_mode_frame.setGeometry(QtCore.QRect(40, 80, 311, 371))
        self.game_mode_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 60, 27);\n"
"}\n"
"")
        self.game_mode_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.game_mode_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.game_mode_frame.setObjectName("game_mode_frame")
        self.game_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.game_mode_label.setGeometry(QtCore.QRect(20, 20, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label.setFont(font)
        self.game_mode_label.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label.setObjectName("game_mode_label")
        self.replay_icon_label = QtWidgets.QLabel(self.game_mode_frame)
        self.replay_icon_label.setGeometry(QtCore.QRect(20, 60, 61, 41))
        self.replay_icon_label.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.replay_icon_label.setText("")
        self.replay_icon_label.setObjectName("replay_icon_label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.game_mode_frame)
        self.stackedWidget.setGeometry(QtCore.QRect(29, 119, 251, 211))
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background-color: rgb(22, 60, 27);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.replay_1_page = QtWidgets.QWidget()
        self.replay_1_page.setStyleSheet("QWidget{\n"
"    background-color: rgb(22, 60, 27);\n"
"}\n"
"QPushButton{\n"
"    background-color: beige;\n"
"    border-radius: 7px;\n"
"    min-height: 20px;\n"
"    color: black;\n"
"}")
        self.replay_1_page.setObjectName("replay_1_page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.replay_1_page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 231, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.game1_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.game1_button.setObjectName("game1_button")
        self.verticalLayout.addWidget(self.game1_button)
        self.game2_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.game2_button.setObjectName("game2_button")
        self.verticalLayout.addWidget(self.game2_button)
        self.game3_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.game3_button.setObjectName("game3_button")
        self.verticalLayout.addWidget(self.game3_button)
        self.game4_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.game4_button.setObjectName("game4_button")
        self.verticalLayout.addWidget(self.game4_button)
        self.stackedWidget.addWidget(self.replay_1_page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.backwards_button = QtWidgets.QPushButton(self.game_mode_frame)
        self.backwards_button.setGeometry(QtCore.QRect(60, 330, 71, 32))
        self.backwards_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/returnleft.png);\n"
"}\n"
"")
        self.backwards_button.setText("")
        self.backwards_button.setObjectName("backwards_button")
        self.forwards_button = QtWidgets.QPushButton(self.game_mode_frame)
        self.forwards_button.setGeometry(QtCore.QRect(180, 330, 71, 32))
        self.forwards_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/returnleft.png);\n"
"}\n"
"")
        self.forwards_button.setText("")
        self.forwards_button.setObjectName("forwards_button")
        self.game_mode_label_2 = QtWidgets.QLabel(self.game_mode_frame)
        self.game_mode_label_2.setGeometry(QtCore.QRect(90, 70, 211, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label_2.setFont(font)
        self.game_mode_label_2.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label_2.setObjectName("game_mode_label_2")
        self.return_to_menu_button = QtWidgets.QPushButton(self.menu_frame)
        self.return_to_menu_button.setGeometry(QtCore.QRect(160, 460, 71, 32))
        self.return_to_menu_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/returnleft.png);\n"
"}\n"
"")
        self.return_to_menu_button.setText("")
        self.return_to_menu_button.setObjectName("return_to_menu_button")
        replay_select_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(replay_select_window)
        QtCore.QMetaObject.connectSlotsByName(replay_select_window)

    def retranslateUi(self, replay_select_window):
        _translate = QtCore.QCoreApplication.translate
        replay_select_window.setWindowTitle(_translate("replay_select_window", "MainWindow"))
        self.name_label.setText(_translate("replay_select_window", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble</span></p><p><br/></p></body></html>"))
        self.game_mode_label.setText(_translate("replay_select_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Obejrzyj powtórkę gry</span></p></body></html>"))
        self.game1_button.setText(_translate("replay_select_window", "PushButton"))
        self.game2_button.setText(_translate("replay_select_window", "PushButton"))
        self.game3_button.setText(_translate("replay_select_window", "PushButton"))
        self.game4_button.setText(_translate("replay_select_window", "PushButton"))
        self.game_mode_label_2.setText(_translate("replay_select_window", "<html><head/><body><p><span style=\" font-size:11pt;\">kliknij przycisk i włącz powtórkę</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    replay_select_window = QtWidgets.QMainWindow()
    ui = Ui_replay_select_window()
    ui.setupUi(replay_select_window)
    replay_select_window.show()
    sys.exit(app.exec())
